version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:7.0
    container_name: curie-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: curie-interview-mvp
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    driver: local 